### ISSUE TITLE
please help me!

### ISSUE THREAD

**Issue by linke131** [UJX6N/bbrplus-6.x_stable#4]
The following error appears when trying to patch
[root@instance-2 linux-6.5.7]# patch -p1 < convert_official_linux-6.5.x_src_to_bbrplus.patch
patch unexpectedly ends in middle of line
patch: **** Only garbage was found in the patch input.
[root@instance-2 linux-6.5.7]#
![IMG_20231018_145910](https://github.com/UJX6N/bbrplus-6.x_stable/assets/145977871/8c8aa399-bd12-4079-81c5-7d3b2c8deea3)

**Comment by UJX6N** [comment]
Try this

`wget https://github.com/linke131/bbrplus-6.x_stable/raw/main/convert_official_linux-6.5.x_src_to_bbrplus.patch`

Size of the pacth file should be around 51KB, not 161KB

**Comment by linke131** [comment]
ok
